bot:
  token: "your bot token"
  prefix: "prefix"
  other:
    invite-bot: "bot invite link"
    invite-support-server: "support server link"

  splashes:
    - "Test splash 1"
    - "Test splash 2"
    - "Test splash 3"


  status_splashes:
    - "Test status splash 1"
    - "Test status splash 2"
    - "Test status splash 3"

mysql:
  host: "127.0.0.1"
  user: "user"
  port: 3306
  password: "password"
  database: "dbName"


redis:
  host: "redis://127.0.0.1"
  port: 6379

lavalink:
  password: "password"